
[build]
command = """
  git clone https://github.com/flutter/flutter.git --depth 1 -b stable
  export PATH="$PATH:`pwd`/flutter/bin"
  flutter doctor
  flutter pub get
  flutter build web
  """
publish = "build/web"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
